engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
  - bin/eslint.js
  - lib/checks.js"
exclude_paths:
- "node_modules/**"
- "test/**"
