---
version: '2'

plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true

exclude_patterns:
  - .common/
  - .config/
  - .go/
  - .modules/
  - .pnpm-store/
  - .venv/
  - deprecated/
  - test-output/
  - venv/
  - _generated_/
