---
stages:
  - update
  - lint
  - test
  - publish
variables:
  PIP_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/pip'
cache:
  key: '${CI_JOB_NAME}'
  paths:
    - .cache/pip
    - .pnpm-store
    - .venv
include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/eslint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/hadolint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/prettier.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/shellcheck.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/yamllint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/semantic-release.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/test/docker/slim.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/update/project.gitlab-ci.yml
integration:standalone:
  image:
    name: megabytelabs/eslint:slim
    entrypoint: ['']
  script:
    - pnpm install eslint-config-strict-mode@latest
    - pnpx eslint -c package.json --no-eslintrc --format gitlab .
integration:codeclimate:
  image: megabytelabs/codeclimate:slim
  script:
    - task lint:codeclimate
